security:
  # Password hashers configuration
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api/
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow access to the API doc without authentication
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow access to the login endpoint
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY } # Protect all other API routes
